# Generated by Django 4.2.4 on 2024-02-29 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the column.', max_length=100, verbose_name='name')),
                ('slug', models.SlugField(help_text='The slug for use in URLs', max_length=100, verbose_name='slug')),
                ('content', models.TextField(blank=True, help_text='The content of the column.  Expected to usually include an iframe or series of iframes')),
                ('order', models.IntegerField(help_text='The order that the column should appear on the page', verbose_name='order')),
                ('width', models.IntegerField(default=1, help_text='The width of the column in multiples of how big it is compared to the narrowest column', verbose_name='width')),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the site.', max_length=100, verbose_name='name')),
                ('slug', models.SlugField(help_text='The slug for use in URLs', max_length=100, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Tagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the tag.', max_length=100, verbose_name='name')),
                ('slug', models.SlugField(help_text='The slug for use in URLs', max_length=100, verbose_name='slug')),
                ('order', models.IntegerField(help_text='The order that the column should appear on the page', verbose_name='order')),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the page.', max_length=100, verbose_name='title')),
                ('slug', models.SlugField(help_text='The slug for use in URLs', max_length=100, verbose_name='slug')),
                ('order', models.IntegerField(help_text='The order that the page would appear in a list', verbose_name='order')),
                ('site', models.ForeignKey(blank=True, help_text='The site to which this page belongs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdc_site.site')),
            ],
            options={
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the column.', max_length=100, verbose_name='name')),
                ('slug', models.SlugField(help_text='The slug for use in URLs', max_length=100, verbose_name='slug')),
                ('order', models.IntegerField(help_text='The order that the column should appear on the page', verbose_name='order')),
                ('width', models.IntegerField(default=1, help_text='The width of the column in multiples of how big it is compared to the narrowest column', verbose_name='width')),
                ('page', models.ForeignKey(blank=True, help_text='The page to which this column belongs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdc_site.page')),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ArticleTagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(help_text='The article to which the tag belongs', on_delete=django.db.models.deletion.CASCADE, to='sdc_site.article')),
                ('tagory', models.ForeignKey(help_text='The tag to which the article belongs', on_delete=django.db.models.deletion.CASCADE, to='sdc_site.tagory')),
            ],
            options={
                'ordering': ('article', 'tagory'),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='page',
            field=models.ForeignKey(blank=True, help_text='The page to which this column belongs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdc_site.page'),
        ),
    ]
