# Generated by Django 4.2.4 on 2024-03-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='content_above_articles',
        ),
        migrations.RemoveField(
            model_name='case',
            name='content_below_articles',
        ),
        migrations.RemoveField(
            model_name='section',
            name='content_after',
        ),
        migrations.RemoveField(
            model_name='section',
            name='content_before',
        ),
        migrations.AddField(
            model_name='case',
            name='content_after_articles',
            field=models.CharField(blank=True, help_text='The content of the case after any included articles', max_length=255),
        ),
        migrations.AddField(
            model_name='case',
            name='content_before_articles',
            field=models.CharField(blank=True, help_text='The content of the case before any included articles', max_length=255),
        ),
        migrations.AddField(
            model_name='section',
            name='content_after_cases',
            field=models.TextField(blank=True, help_text='content to be displayed after the cases'),
        ),
        migrations.AddField(
            model_name='section',
            name='content_before_cases',
            field=models.TextField(blank=True, help_text='content to be displayed before the cases'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text='The content of the article.  Expected to usually include an iframe or series of iframes'),
        ),
    ]
