# Generated by Django 4.2.4 on 2024-03-07 20:03

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-publish_date', 'title')},
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ('order', 'name')},
        ),
        migrations.AddField(
            model_name='article',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date/time that this article was created', verbose_name='date/time created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateField(default=datetime.date.today, help_text='The published date, which can be filled in by the editors.  Used for sorting when more than one article is in a case.', verbose_name='published'),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, help_text='The date/time that this article was updated', verbose_name='date/time updated'),
        ),
        migrations.AddField(
            model_name='case',
            name='order',
            field=models.IntegerField(default=0, help_text='A number used for ordering of the case in a section', verbose_name='order'),
        ),
        migrations.AddField(
            model_name='case',
            name='show_article_meta',
            field=models.CharField(choices=[('ad', 'Author and Date'), ('a0', 'Author'), ('0d', 'Publish Date')], default='ad', help_text='What article information should be shown for aticles in cases', max_length=2, verbose_name='show article meta'),
        ),
    ]
