# Generated by Django 4.2.4 on 2024-02-29 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='The label of this menu item', max_length=30, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='MenuPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(help_text='The menu that is attached to this page', on_delete=django.db.models.deletion.CASCADE, to='sdc_site.menu')),
                ('page', models.ForeignKey(help_text='The page that this menu is attached to ', on_delete=django.db.models.deletion.CASCADE, to='sdc_site.page')),
            ],
        ),
        migrations.CreateModel(
            name='Menuitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.URLField(blank=True, help_text='The URL that this menu item points to', verbose_name='href')),
                ('label', models.CharField(blank=True, help_text='The label of this menu item', max_length=30, verbose_name='label')),
                ('menu', models.ForeignKey(blank=True, help_text='The menu to which this item belongs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdc_site.menu')),
            ],
        ),
    ]
