# Generated by Django 4.2.4 on 2024-03-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0002_alter_article_options_alter_case_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='show_article_meta',
            field=models.CharField(choices=[('00', 'None'), ('a0', 'Author'), ('0d', 'Publish Date'), ('ad', 'Author and Date')], default='00', help_text='What article meta information should be shown for aticles in cases', max_length=2, verbose_name='show article meta'),
        ),
    ]
