# Generated by Django 4.2.4 on 2024-03-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0002_menu_menupage_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='The slug for use in URLs', max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='column',
            name='slug',
            field=models.SlugField(help_text='The slug for use in URLs', max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text='The slug for use in URLs', max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.SlugField(help_text='The slug for use in URLs', max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='tagory',
            name='slug',
            field=models.SlugField(help_text='The slug for use in URLs', max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
