# Generated by Django 4.2.4 on 2024-03-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0003_alter_article_slug_alter_column_slug_alter_page_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='content',
            field=models.TextField(blank=True, help_text='The content of the column.  Expected to usually include an iframe or series of iframes'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text='The content of the article.'),
        ),
    ]
