# Generated by Django 4.2.4 on 2024-03-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0004_section_show_title_alter_section_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ('section', 'order', 'name')},
        ),
        migrations.AlterModelOptions(
            name='casearticle',
            options={'ordering': ('case', 'article')},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('page', 'order', 'name')},
        ),
        migrations.AddField(
            model_name='page',
            name='is_home',
            field=models.BooleanField(default=False, help_text='If this is the home page', verbose_name='is home page'),
        ),
        migrations.AlterField(
            model_name='section',
            name='show_title',
            field=models.BooleanField(default=True, help_text='Show the name of the section as a title', verbose_name='show title'),
        ),
    ]
