# Generated by Django 4.2.4 on 2024-03-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0004_column_content_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='href',
            field=models.CharField(blank=True, help_text='The URL that this menu item points to', max_length=255, verbose_name='href'),
        ),
    ]
