# Generated by Django 4.2.4 on 2024-03-01 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0005_alter_menuitem_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='page',
        ),
        migrations.AlterField(
            model_name='column',
            name='order',
            field=models.IntegerField(help_text='The order that the column should appear in the section', verbose_name='order'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the section.', max_length=100, verbose_name='name')),
                ('slug', models.SlugField(help_text='The slug for use in URLs', max_length=100, unique=True, verbose_name='slug')),
                ('order', models.IntegerField(help_text='The order that the section should appear on the page', verbose_name='order')),
                ('content_before', models.TextField(blank=True, help_text='content to be displayed above the columns')),
                ('content_after', models.TextField(blank=True, help_text='content to be displayed below the columns')),
                ('page', models.ForeignKey(blank=True, help_text='The page to which this column belongs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdc_site.page')),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='column',
            name='section',
            field=models.ForeignKey(blank=True, help_text='The section to which this column belongs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdc_site.section'),
        ),
    ]
