# Generated by Django 4.2.4 on 2024-03-07 23:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sdc_site", "0005_alter_case_options_alter_casearticle_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Case", new_name="Rack"),
        migrations.AlterField(
            model_name="rack",
            name="name",
            field=models.CharField(
                help_text="The name of the rack.", max_length=100, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="rack",
            name="width",
            field=models.IntegerField(
                default=1,
                help_text="The width of the rack in multiples of how big it is compared to the narrowest rack",
                verbose_name="width",
            ),
        ),
        migrations.AlterField(
            model_name="rack",
            name="show_article_meta",
            field=models.CharField(
                choices=[
                    ("00", "None"),
                    ("a0", "Author"),
                    ("0d", "Publish Date"),
                    ("ad", "Author and Date"),
                ],
                default="00",
                help_text="What article meta information should be shown for aticles in racks",
                max_length=2,
                verbose_name="show article meta",
            ),
        ),
        migrations.AlterField(
            model_name="rack",
            name="content_before_articles",
            field=models.CharField(
                blank=True,
                help_text="The content of the rack before any included articles",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="rack",
            name="content_after_articles",
            field=models.CharField(
                blank=True,
                help_text="The content of the rack after any included articles",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="rack",
            name="order",
            field=models.IntegerField(
                default=0,
                help_text="A number used for ordering of the rack in a section",
                verbose_name="order",
            ),
        ),
        migrations.AlterField(
            model_name="rack",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="The section to which the rack belongs",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sdc_site.section",
            ),
        ),
        migrations.RenameModel(old_name="CaseArticle", new_name="RackArticle"),
        migrations.RenameField(
            model_name="rackarticle", old_name="case", new_name="rack"
        ),
        migrations.AlterModelOptions(
            name="rackarticle",
            options={
                "ordering": ("rack", "article"),
            },
        ),
        migrations.RenameField(
            model_name="section",
            old_name="content_after_cases",
            new_name="content_after_racks",
        ),
        migrations.AlterField(
            model_name="section",
            name="content_after_racks",
            field=models.TextField(
                blank=True, help_text="content to be displayed after the racks"
            ),
        ),
        migrations.RenameField(
            model_name="section",
            old_name="content_before_cases",
            new_name="content_before_racks",
        ),
        migrations.AlterField(
            model_name="section",
            name="content_before_racks",
            field=models.TextField(
                blank=True, help_text="content to be displayed before the racks"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="order",
            field=models.IntegerField(
                default=0,
                help_text="The order that the article would appear in the rack",
                verbose_name="order",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="publish_date",
            field=models.DateField(
                default=datetime.date.today,
                help_text="The published date, which can be filled in by the editors.  Used for sorting when more than one article is in a rack.",
                verbose_name="published",
            ),
        ),
    ]
