# Generated by Django 4.2.4 on 2024-03-01 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0006_remove_column_page_alter_column_order_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='section',
        ),
        migrations.CreateModel(
            name='SectionColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.ForeignKey(help_text='The column which appears in the section', on_delete=django.db.models.deletion.CASCADE, to='sdc_site.column')),
                ('section', models.ForeignKey(help_text='The section to which the column belongs', on_delete=django.db.models.deletion.CASCADE, to='sdc_site.section')),
            ],
        ),
    ]
