# Generated by Django 4.2.4 on 2024-03-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0006_rack_rackarticle_remove_casearticle_article_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rackarticle',
            options={'ordering': ('rack', 'order', 'article')},
        ),
        migrations.AddField(
            model_name='rackarticle',
            name='order',
            field=models.IntegerField(default=0, help_text='A number used to order the articles, overriding the default', verbose_name='order'),
        ),
    ]
