# Generated by Django 4.2.4 on 2024-03-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sdc_site", "0007_alter_rackarticle_options_rackarticle_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="order",
        ),
    ]
