# Generated by Django 4.2.4 on 2024-03-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0007_remove_column_section_sectioncolumn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('order', 'title')},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='title',
        ),
    ]
