# Generated by Django 4.2.4 on 2024-03-08 10:21

from django.db import migrations, models


def move_height_from_src_to_height(apps, schema_editor):
    Article = apps.get_model("sdc_site", "Article")
    for article in Article.objects.all():
        iframe_parts = article.iframe_src.split(" ")
        if len(iframe_parts) > 0:
            article.iframe_src = iframe_parts[0]
        if len(iframe_parts) > 1:
            article.iframe_height = iframe_parts[1]
        article.save()


class Migration(migrations.Migration):

    dependencies = [
        ("sdc_site", "0008_remove_article_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="iframe_height",
            field=models.CharField(
                blank=True,
                help_text="The height of the iframe using css height syntax.  Blank to use values set in stylesheets",
                max_length=20,
                verbose_name="iframe height",
            ),
        ),
        migrations.RunPython(move_height_from_src_to_height),
    ]
