# Generated by Django 4.2.4 on 2024-03-02 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0009_alter_article_options_alter_column_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectioncolumn',
            options={'ordering': ('order', 'section', 'order')},
        ),
    ]
