# Generated by Django 4.2.4 on 2024-03-03 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0010_alter_sectioncolumn_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The name of the column.', max_length=100, verbose_name='name')),
                ('content', models.TextField(blank=True, help_text='The content of the column.  Expected to usually include an iframe or series of iframes')),
                ('order', models.IntegerField(default=0, help_text='The order that the segment would appear in the column', verbose_name='order')),
                ('column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdc_site.column')),
            ],
        ),
    ]
