# Generated by Django 4.2.4 on 2024-03-08 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0010_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='iframe_document',
            field=models.ForeignKey(blank=True, help_text='If selected, the document to be displayed in the iframe.  This will take precedence over anything entered in the iframe source field', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdc_site.document'),
        ),
    ]
