# Generated by Django 5.0.3 on 2024-03-10 00:40

import django.db.models.deletion
from django.db import migrations, models


def populate_slug_fields(apps, schema_editor):
    Document = apps.get_model("sdc_site", "Document")
    for document in Document.objects.all():
        if document.slug == "":
            document.slug = "{}".format(document.pk)
            document.save


class Migration(migrations.Migration):

    dependencies = [
        ("sdc_site", "0011_article_iframe_document"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="site",
        ),
        migrations.RemoveField(
            model_name="document",
            name="name",
        ),
        migrations.RemoveField(
            model_name="section",
            name="show_title",
        ),
        migrations.AddField(
            model_name="document",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="The name or slug for use in URLs and within the application (must be unique and conform to slug standards)",
                max_length=100,
                verbose_name="name/slug",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="The title to be displayed with document.  It may or may not correspond to anything in the document itself. (can be blank)",
                max_length=100,
                verbose_name="title",
            ),
        ),
        migrations.AddField(
            model_name="rack",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="The title of the rack to be displayed (can be blank)",
                max_length=100,
                verbose_name="title",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="The title of the page. to be displayed (can be blank)",
                max_length=100,
                verbose_name="title",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="content_classes",
            field=models.CharField(
                blank=True,
                default="article-content uldoc",
                help_text="HTML classes to be applied to the content (default: article-content uldoc)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                help_text="The name or slug for use in URLs and within the application (must be unique and conform to slug standards)",
                max_length=100,
                unique=True,
                verbose_name="name/slug",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(
                help_text="The name or slug for use in URLs and within the application (must be unique and conform to slug standards)",
                max_length=100,
                unique=True,
                verbose_name="name/slug",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(
                help_text="The title of the page. to be displayed (can be blank)",
                max_length=100,
                verbose_name="title",
            ),
        ),
        migrations.AlterField(
            model_name="rack",
            name="slug",
            field=models.SlugField(
                help_text="The name or slug for use in URLs and within the application (must be unique and conform to slug standards)",
                max_length=100,
                unique=True,
                verbose_name="name/slug",
            ),
        ),
        migrations.AlterField(
            model_name="rackarticle",
            name="article",
            field=models.ForeignKey(
                blank=True,
                help_text="The article in the rack",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sdc_site.article",
            ),
        ),
        migrations.AlterField(
            model_name="rackarticle",
            name="rack",
            field=models.ForeignKey(
                blank=True,
                help_text="The rack that holds the article",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sdc_site.rack",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="slug",
            field=models.SlugField(
                help_text="The name or slug for use in URLs and within the application (must be unique and conform to slug standards)",
                max_length=100,
                unique=True,
                verbose_name="name/slug",
            ),
        ),
        migrations.DeleteModel(
            name="Site",
        ),
    ]
