# Generated by Django 4.2.4 on 2024-03-03 22:29

from django.db import migrations


def copy_column_content_to_new_segment(apps, schema_editor):
    Column = apps.get_model("sdc_site", "Column")
    Segment = apps.get_model("sdc_site", "Segment")

    for column in Column.objects.all():
        if column.content > "":
            title = ""
            if column.content:
                if (
                    column.content.find("<h2>") > -1
                    and column.content.find("</h2>") > -1
                ):
                    title = column.content[
                        column.content.find("<h2>") + 4 : column.content.find("</h2>")
                    ]
                segment = Segment.objects.create(
                    content=column.content, title=title, column=column
                )
                segment.save()


class Migration(migrations.Migration):

    dependencies = [
        ("sdc_site", "0011_segment"),
    ]

    operations = [
        migrations.RunPython(copy_column_content_to_new_segment),
    ]
