# Generated by Django 4.2.4 on 2024-03-04 00:06

from django.db import migrations


def remove_h2(apps, schema_editor):
    Segment = apps.get_model("sdc_site", "Segment")

    for segment in Segment.objects.all():
        if segment.content > "":
            if segment.content.find("<h2>") > -1 and segment.content.find("</h2>") > -1:
                segment.content = (
                    segment.content[1 : segment.content.find("<h2>")]
                    + segment.content[segment.content.find("</h2>") + 5 :]
                ).strip()
                segment.save()
            segment.column.content = ""
            segment.column.save()


class Migration(migrations.Migration):

    dependencies = [
        ("sdc_site", "0012_auto_20240303_1729"),
    ]

    operations = [
        migrations.RunPython(remove_h2),
    ]
