# Generated by Django 5.0.3 on 2024-03-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0012_remove_page_site_remove_document_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rack',
            options={'ordering': ('section', 'order')},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('page', 'order')},
        ),
        migrations.RemoveField(
            model_name='rack',
            name='name',
        ),
        migrations.RemoveField(
            model_name='section',
            name='name',
        ),
        migrations.AddField(
            model_name='document',
            name='show_title',
            field=models.BooleanField(default=True, help_text='If the title should be shown (if not blank)', verbose_name='show title'),
        ),
        migrations.AddField(
            model_name='page',
            name='show_title',
            field=models.BooleanField(default=True, help_text='If the title should be shown (if not blank)', verbose_name='show title'),
        ),
        migrations.AddField(
            model_name='rack',
            name='show_title',
            field=models.BooleanField(default=True, help_text='If the title should be shown (if not blank)', verbose_name='show title'),
        ),
        migrations.AddField(
            model_name='section',
            name='show_title',
            field=models.BooleanField(default=True, help_text='If the title should be shown (if not blank)', verbose_name='show title'),
        ),
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, help_text='The name or slug for use in URLs and within the application (must be unique and conform to slug standards)', max_length=100, unique=True, verbose_name='name/slug'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, help_text='The title of the page. to be displayed (can be blank)', max_length=100, verbose_name='title'),
        ),
    ]
