# Generated by Django 5.0.3 on 2024-03-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0013_alter_rack_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='display',
            field=models.CharField(choices=[('Y', 'Normal'), ('P', 'Preview Only'), ('H', 'Hide from Racks'), ('N', 'Do not display')], default='Y', help_text='How the section should be displayed.  If hidden from racks, the article may still be found by other means', max_length=2, verbose_name='display'),
        ),
        migrations.AddField(
            model_name='page',
            name='display',
            field=models.CharField(choices=[('Y', 'Normal'), ('H', 'Hide from Menus'), ('N', 'Do not display')], default='Y', help_text='How the page should be displayed', max_length=2, verbose_name='display'),
        ),
        migrations.AddField(
            model_name='rack',
            name='display',
            field=models.CharField(choices=[('Y', 'Normal'), ('P', 'Preview Only'), ('H', 'Hide from sections'), ('N', 'Do not display')], default='Y', help_text='How the rack should be displayed. Racks that are hidden from sections may still be displayed independently', max_length=2, verbose_name='display'),
        ),
        migrations.AddField(
            model_name='section',
            name='display',
            field=models.CharField(choices=[('Y', 'Normal'), ('P', 'Preview Only'), ('N', 'Do not display')], default='Y', help_text='How the section should be displayed', max_length=2, verbose_name='display'),
        ),
    ]
