# Generated by Django 4.2.4 on 2024-03-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0015_auto_20240305_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='slug',
            field=models.SlugField(help_text='The slug for use in URLs', max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
