# Generated by Django 5.0.3 on 2024-03-13 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0015_remove_article_content_format_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='preview_for',
            field=models.ForeignKey(blank=True, help_text='The target rack if this rack is a preview for another.  The intent in this case is for you to fill out content before article', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdc_site.rack'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='content_after_articles',
            field=models.CharField(blank=True, help_text='The content of the rack after any included articles', max_length=255, verbose_name='content after articles'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='content_before_articles',
            field=models.CharField(blank=True, help_text='The content of the rack before any included articles', max_length=255, verbose_name='content before articles'),
        ),
    ]
