# Generated by Django 5.0.3 on 2024-03-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0016_rack_preview_for_alter_rack_content_after_articles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='level',
            field=models.IntegerField(default=0, help_text='A number used to help determine on which pages the menu should appear. Positive numbers are intended for menus which should appear on all or most pages', verbose_name='level'),
        ),
    ]
