# Generated by Django 4.2.4 on 2024-03-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0016_alter_segment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='iframe_src',
            field=models.CharField(blank=True, help_text='The URL of a Google script, if the script is to be displayed in an iframe, optionally followed by a css height value', max_length=255, verbose_name='script_id'),
        ),
    ]
