# Generated by Django 5.0.3 on 2024-03-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0017_menu_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('-level',)},
        ),
        migrations.AlterField(
            model_name='menu',
            name='level',
            field=models.IntegerField(default=0, help_text='A number, like an id (but not unique enforced), which can be used for the page to indentify the menu. Use of 1000 for the main menu is recommended', verbose_name='level'),
        ),
    ]
