# Generated by Django 4.2.4 on 2024-03-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0017_segment_iframe_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='content',
            field=models.TextField(blank=True, help_text='The content of the column.  '),
        ),
        migrations.AlterField(
            model_name='segment',
            name='iframe_src',
            field=models.CharField(blank=True, help_text='If an iframe is to be displayed, the URL of an approved iframe source (must be listed in settings), optionally followed by a css height value', max_length=255, verbose_name='iframe source'),
        ),
    ]
