# Generated by Django 5.0.3 on 2024-03-13 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sdc_site", "0018_alter_menu_options_alter_menu_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="content_classes",
        ),
        migrations.AddField(
            model_name="article",
            name="can_contain_articles",
            field=models.BooleanField(
                default=False,
                help_text="If this article can contain other articles",
                verbose_name="Can Contain Articles",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="preview_for",
            field=models.ForeignKey(
                blank=True,
                help_text="The target rack if this rack is a preview for another.  The intent in this case is for you to fill out content before article",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sdc_site.rack",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="The section to which the article belongs if directly attached to a section",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sdc_site.section",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="show_title",
            field=models.BooleanField(
                default=True,
                help_text="If the title should be shown (if not blank)",
                verbose_name="show title",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="width",
            field=models.IntegerField(
                default=1,
                help_text="For section display, the width of the article in multiples of how big it is compared to the narrowest article in the section",
                verbose_name="width",
            ),
        ),
        migrations.AddField(
            model_name="rackarticle",
            name="container",
            field=models.ForeignKey(
                blank=True,
                help_text="The container article that holds the target article",
                limit_choices_to={"can_contain_articles": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="to_target_article",
                to="sdc_site.article",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="show_contained_article_meta",
            field=models.IntegerField(
                choices=[
                    (0, "None"),
                    (1, "Author"),
                    (2, "Publish Date"),
                    (3, "Author and Date"),
                ],
                default=0,
                help_text="What article meta information should be shown for aticles in racks",
                verbose_name="show article meta",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(blank=True, help_text="The content of the article"),
        ),
        migrations.AlterField(
            model_name="rackarticle",
            name="article",
            field=models.ForeignKey(
                blank=True,
                help_text="The article held by the containing article",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="to_containing_article",
                to="sdc_site.article",
            ),
        ),
    ]
