# Generated by Django 4.2.4 on 2024-03-07 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sdc_site", "0018_alter_column_content_alter_segment_iframe_src"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Segment",
            new_name="Article",
        ),
    ]
