# Generated by Django 5.0.3 on 2024-03-13 13:07

from django.db import migrations


def make_articles_to_replace_racks(apps, schema_editor):
    Rack = apps.get_model("sdc_site", "Rack")
    Article = apps.get_model("sdc_site", "Article")
    RackArticle = apps.get_model("sdc_site", "RackArticle")

    unique_num = 0
    for rack in Rack.objects.all():
        unique_num = unique_num + 1
        containing_article = Article.objects.create(
            title=rack.title,
            show_title=rack.show_title,
            slug=rack.slug + str(unique_num),
            section=rack.section,
            width=rack.width,
            content=rack.content_before_articles,
            can_contain_articles=True,
        )
        for rackarticle in rack.rackarticle_set.all():
            rackarticle.container = containing_article
            rackarticle.save()


class Migration(migrations.Migration):

    dependencies = [
        ("sdc_site", "0019_prepare_removal_of_rack_"),
    ]

    operations = [migrations.RunPython(make_articles_to_replace_racks)]
