# Generated by Django 4.2.4 on 2024-03-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0019_auto_20240307_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='content',
        ),
        migrations.AddField(
            model_name='column',
            name='content_above_articles',
            field=models.CharField(blank=True, help_text='The content of the column above any included articles', max_length=255),
        ),
        migrations.AddField(
            model_name='column',
            name='content_below_articles',
            field=models.CharField(blank=True, help_text='The content of the column below any included articles', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_classes',
            field=models.CharField(blank=True, default='article-content uldoc', help_text='HTML classes to be applied to the content (default: article-content uldoc)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='order',
            field=models.IntegerField(default=0, help_text='The order that the article would appear in the column', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='The name of the article.', max_length=100, verbose_name='title'),
        ),
    ]
