# Generated by Django 5.0.3 on 2024-04-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0020_auto_20240313_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='can_contain_articles',
        ),
        migrations.RemoveField(
            model_name='article',
            name='preview_for',
        ),
        migrations.RemoveField(
            model_name='article',
            name='show_contained_article_meta',
        ),
        migrations.RemoveField(
            model_name='rack',
            name='preview_for',
        ),
        migrations.RemoveField(
            model_name='rackarticle',
            name='container',
        ),
        migrations.AddField(
            model_name='article',
            name='if_summary_blank',
            field=models.IntegerField(choices=[(0, 'Show Blank'), (1, 'Show Content')], default=1, help_text='What to display if the summary is blank', verbose_name='If summary is blank'),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, help_text='A summary of the content of the article', verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text='The content of the article', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='display',
            field=models.CharField(choices=[('Y', 'Normal'), ('P', 'Preview Only'), ('N', 'Do not display')], default='Y', help_text='How the section should be displayed.  If hidden from racks, the article may still be found by other means', max_length=2, verbose_name='display'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='display',
            field=models.CharField(choices=[('Y', 'Normal'), ('P', 'Preview Only'), ('N', 'Do not display')], default='Y', help_text='How the rack should be displayed. Racks that are hidden from sections may still be displayed independently', max_length=2, verbose_name='display'),
        ),
    ]
