# Generated by Django 5.0.3 on 2024-04-04 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0021_remove_article_can_contain_articles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='section',
        ),
    ]
