# Generated by Django 4.2.4 on 2024-03-07 15:54

from django.db import migrations, models
import django.db.models.deletion


def create_case_articles(apps, schema_editor):
    Article = apps.get_model("sdc_site", "Article")
    CaseArticle = apps.get_model("sdc_site", "CaseArticle")

    for article in Article.objects.all():

        CaseArticle.objects.create(
            article=article,
            case=article.case,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("sdc_site", "0021_auto_20240307_0936"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ("order", "title")},
        ),
        migrations.CreateModel(
            name="CaseArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sdc_site.article",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sdc_site.case",
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_case_articles),
        migrations.RemoveField(
            model_name="article",
            name="case",
        ),
    ]
