# Generated by Django 4.2.4 on 2024-03-07 16:40

from django.db import migrations, models
import django.db.models.deletion


def populate_case_section(apps, schema_editor):
    SectionCase = apps.get_model("sdc_site", "SectionCase")
    Case = apps.get_model("sdc_site", "Case")
    for sectioncase in SectionCase.objects.all():
        try:
            case = Case.objects.get(pk=sectioncase.case)
            case.section = sectioncase.section
            case.save()
        except:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("sdc_site", "0022_alter_article_options_remove_article_case_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="The section to which the case belongs",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sdc_site.section",
            ),
        ),
        migrations.RunPython(populate_case_section),
        migrations.DeleteModel(
            name="SectionCase",
        ),
    ]
