# Generated by Django 5.0.3 on 2024-04-04 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0022_remove_article_section'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RackArticle',
            new_name='Hanger',
        ),
    ]
