# Generated by Django 5.0.3 on 2024-05-04 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0027_rack_collapse_section_collapse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hanger',
            name='article',
            field=models.ForeignKey(blank=True, help_text='The article held by the containing article', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sdc_site.article'),
        ),
    ]
