# Generated by Django 5.0.3 on 2024-05-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_site', '0028_alter_hanger_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sdcimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagefile', models.ImageField(upload_to='sdc_siteimages', verbose_name='file')),
                ('name', models.CharField(help_text='The name to be used by authors to identify the image', max_length=20, unique=True, verbose_name='name')),
                ('alt_text', models.TextField(help_text='The default alt-text to be redered in the template.  This is the text displayed for the visually impaired', verbose_name='alt text')),
                ('title', models.CharField(blank=True, help_text='The default title of the image to be used in rendering.  This is a tool-tip that appears when the user holds the mouse pointer over the image', max_length=80, verbose_name='title')),
            ],
        ),
    ]
